stages:
  - prepare
  - build

variables:
  REGISTRY: "$CI_REGISTRY"
  IMAGE_NAME: "$CI_PROJECT_PATH"
  # DOCKER_HOST: tcp://docker:2375/
  # DOCKER_TLS_CERTDIR: ""

default:
  image: gitlab.tikalk.dev:5050/tikalk/engineering/bootstrap/tools/main:latest
  services:
    - docker:dind

before_script:
  - apk add --no-cache curl jq nodejs npm git

prepare:
  stage: prepare
  script:
    - echo "Preparing environment"
    - calculatedSha=$(git rev-parse --short $CI_COMMIT_SHA)
    - echo "short_sha=$calculatedSha" >> vars.env
    - echo $calculatedSha
    - export SHORT_SHA=$calculatedSha
  artifacts:
    reports:
      dotenv: vars.env


semantic_release_prep:
  stage: prepare
  script:
    - npm install -g semantic-release
    - npm install -g @semantic-release/git @semantic-release/github @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec
    - |
      cat <<EOF > .releaserc.yml
      branches:
        - main
        - name: dev
          prerelease: true
      plugins:
        - "@semantic-release/commit-analyzer"
        - "@semantic-release/release-notes-generator"
        - "@semantic-release/git"
        - "@semantic-release/github"
        - - "@semantic-release/exec"
          - verifyReleaseCmd: echo \${nextRelease.version} > nextVersion
      EOF
    - semantic-release --dry-run
    - if [ -f nextVersion ]; then echo "SRTAG=v$(cat nextVersion)" >> vars.env; else echo "SRTAG=$SHORT_SHA" >> vars.env; fi
  artifacts:
    reports:
      dotenv: vars.env


build_and_push:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    # - sleep 20 
    # - docker buildx create --use
    # - docker buildx inspect --bootstrap
    - |
      docker buildx build --platform linux/amd64,linux/arm64 \
        --build-arg SRTAG=$SRTAG \
        --tag $REGISTRY/$IMAGE_NAME:latest \
        --tag $REGISTRY/$IMAGE_NAME:latest-$CI_COMMIT_REF_NAME \
        --tag $REGISTRY/$IMAGE_NAME:$SRTAG \
        --push .
  only:
    refs:
      - branches


