stages:
  - prepare
  - build

variables:
  REGISTRY: "$CI_REGISTRY"
  IMAGE_NAME: "$CI_PROJECT_PATH"

default:
  image: gitlab.tikalk.dev:5050/tikalk/engineering/bootstrap/tools/main:latest
  services:
    - docker:dind

before_script:
  - apk add --no-cache curl jq nodejs npm git

prepare:
  stage: prepare
  script:
    - echo "Preparing environment"
    - calculatedSha=$(git rev-parse --short $CI_COMMIT_SHA)
    - echo "short_sha=$calculatedSha" >> vars.env
    - export SHORT_SHA=$calculatedSha
  artifacts:
    reports:
      dotenv: vars.env

# build_and_push:
#   stage: build
#   script:
#     - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
#     - docker buildx create --use
#     - docker buildx inspect --bootstrap
#     - |
#       docker buildx build --platform linux/amd64,linux/arm64 \
#         --build-arg SRTAG=$SRTAG \
#         --tag $REGISTRY/$IMAGE_NAME:latest \
#         --tag $REGISTRY/$IMAGE_NAME:latest-$CI_COMMIT_REF_NAME \
#         --tag $REGISTRY/$IMAGE_NAME:$SRTAG \
#         --push .
#   only:
#     refs:
#       - branches


